config/routes.rb
Rails.application.routes.draw do

  resources :products

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
  has_and_belongs_to_many :products

  validates_presence_of :name
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id         :integer          not null, primary key
#  name       :string
#  price      :decimal(, )
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Product < ActiveRecord::Base
  has_and_belongs_to_many :categories

  validates_presence_of :name, :price

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, except: [:index, :create, :new]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path, notice: "The product was successfully created"
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to products_path, notice: "The product was successfully updated"
    else
      render 'edit'
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path, notice: "The product was successfully deleted"
  end

  private
    def product_params
      params.require(:product).permit(:name, :price, category_ids: [])
    end

    def set_product
      @product = Product.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def form_title
    @product.new_record? ? "Nuevo Producto" : "Editar Producto"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reto13</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:notice] %>
  <div class="alert alert-info">
    <a href="#" class="close" data-dismiss="alert">&#215;</a>
    <%= flash[:notice] %>
  </div>
<% end %>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/products/_form.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <h1><%= form_title %></h1>
    <%= form_for @product do |f| %>
      <div class="form-group">
        <%= f.text_field :name, class:"form-control", placeholder: "Nombre del producto" %>
      </div>
        <div class="form-group">
          <%= f.number_field :price, class:"form-control", placeholder: "Precio del producto" %>
        </div>
        <div class="form-group">
          <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |c| %>
          <!-- Poner las CATEGORIES en vertical -->
            <div class="checkbox">
               <%= c.label do %>
                 <%= c.check_box %> <%= c.object.name %>
               <% end %>
             </div>
          <% end %>
        </div>
        <div class="form-group">
          <%= f.submit class:"btn btn-primary btn-block" %>
        </div>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<h1>Products</h1>
<div class="text-right">
  <%= link_to "Nuevo Producto", new_product_path, class: "btn btn-primary" %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Precio</th>
      <th>Categorias</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.name, product %></td>
        <td><%= number_to_currency(product.price, precision: 2) %></td>
        <td>
          <!-- Se usa PLUCK para arrancar un atributo a la clase -->
          <%= product.categories.pluck(:name).join(', ') %>
          <!-- <% product.categories.each do |category| %>
            <%= category.name %>,
          <% end %> -->
        </td>
        <td>
          <%= link_to "Editar", edit_product_path(product) %>
          <%= link_to "Eliminar", product_path(product), method: :delete, data: {confirm: "Are you sure?"} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<%= render 'form' %>

app/views/products/show.html.erb
<h1>SHOW</h1>